#!/usr/bin/env node
/**
 * Ingest consolidated custom slide layouts and rels from two TXT files
 * and generate the TS registries used by the library:
 *  - src/cust-xml-slide-layouts.ts
 *  - src/cust-xml-slide-layout-rels.ts
 *
 * Usage:
 *   node tools/ingest-layouts.mjs <layouts.txt> <rels.txt>
 *
 * TXT formats:
 *
 * layouts.txt
 *   --- layout:id=1 name=Content - no subtitle ---
 *   <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 *   <p:sldLayout ...> ... </p:sldLayout>
 *   --- layout:id=2 name=Title and Content ---
 *   <p:sldLayout ...> ... </p:sldLayout>
 *   ...
 *
 * rels.txt
 *   --- rels:id=1 ---
 *   <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 *   <Relationships ...>
 *     <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/>
 *   </Relationships>
 *   --- rels:id=2 ---
 *   <Relationships ...> ... </Relationships>
 *   ...
 */

import { readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { resolve } from 'node:path'

const WORKSPACE_ROOT = resolve(process.cwd())
const OUT_LAYOUTS_TS = resolve(WORKSPACE_ROOT, 'src/cust-xml-slide-layouts.ts')
const OUT_RELS_TS = resolve(WORKSPACE_ROOT, 'src/cust-xml-slide-layout-rels.ts')

function die(msg) {
  console.error(`[ingest-layouts] ERROR: ${msg}`)
  process.exit(1)
}

function escapeTemplate(str) {
  return String(str).replace(/`/g, '\\`')
}

function parseLayouts(text) {
  const entries = []
  const lines = text.split(/\r?\n/)
  let i = 0
  while (i < lines.length) {
    const header = lines[i].trim()
    if (!header.startsWith('--- layout:')) { i++; continue }
    const m = header.match(/^---\s*layout:id=(\d+)\s+name=(.*?)\s*---\s*$/)
    if (!m) die(`Invalid layout header format at line ${i + 1}: ${header}`)
    const id = Number(m[1])
    const name = m[2]
    i++
    const body = []
    while (i < lines.length && !lines[i].trim().startsWith('--- layout:')) {
      if (lines[i].trim().startsWith('--- rels:')) break
      body.push(lines[i])
      i++
    }
    const xml = body.join('\n').trim()
    if (!xml) die(`Empty layout XML for id=${id}`)
    entries.push({ id, name, xml })
  }
  return entries
}

function parseRels(text) {
  const entries = []
  const lines = text.split(/\r?\n/)
  let i = 0
  while (i < lines.length) {
    const header = lines[i].trim()
    if (!header.startsWith('--- rels:')) { i++; continue }
    const m = header.match(/^---\s*rels:id=(\d+)\s*---\s*$/)
    if (!m) die(`Invalid rels header format at line ${i + 1}: ${header}`)
    const id = Number(m[1])
    i++
    const body = []
    while (i < lines.length && !lines[i].trim().startsWith('--- rels:')) {
      if (lines[i].trim().startsWith('--- layout:')) break
      body.push(lines[i])
      i++
    }
    const relsXml = body.join('\n').trim()
    if (!relsXml) die(`Empty rels XML for id=${id}`)
    entries.push({ id, relsXml })
  }
  return entries
}

function validate(entries, rels) {
  const ids = new Set(entries.map(e => e.id))
  if (ids.size !== entries.length) die('Duplicate layout ids detected')
  const relIds = new Set(rels.map(r => r.id))
  if (relIds.size !== rels.length) die('Duplicate rels ids detected')
  const missingRels = entries.filter(e => !relIds.has(e.id)).map(e => e.id)
  if (missingRels.length) die(`Missing rels for layout ids: ${missingRels.join(', ')}`)

  // Basic safety: ensure slideMaster relationship is present in each rels block
  const noMaster = rels.filter(r => !/slideMaster\"|slideMaster\'|slideMaster<|slideMaster/.test(r.relsXml) || !/Target=\"\.\.\/slideMasters\/slideMaster1\.xml\"/.test(r.relsXml))
  if (noMaster.length) {
    console.warn(`[ingest-layouts] WARNING: ${noMaster.length} rels entries do not appear to reference slideMaster1.xml. Double-check targets.`)
  }
}

function generateLayoutsTs(entries) {
  const header = `// AUTO-GENERATED by tools/ingest-layouts.mjs\n// DO NOT EDIT MANUALLY\n\nexport type CustomSlideLayoutDef = { id: number; name: string; xml: string }\n\nexport const CUSTOM_SLIDE_LAYOUT_DEFS: CustomSlideLayoutDef[] = [\n`
  const body = entries
    .sort((a, b) => a.id - b.id)
    .map(e => `  { id: ${e.id}, name: ${JSON.stringify(e.name)}, xml: \`${escapeTemplate(e.xml)}\` },`)
    .join('\n')
  const footer = `\n]\n`
  return header + body + footer
}

function generateRelsTs(entries) {
  const header = `// AUTO-GENERATED by tools/ingest-layouts.mjs\n// DO NOT EDIT MANUALLY\n\nexport type CustomSlideLayoutRelDef = { id: number; relsXml: string }\n\nexport const CUSTOM_SLIDE_LAYOUT_RELS: CustomSlideLayoutRelDef[] = [\n`
  const body = entries
    .sort((a, b) => a.id - b.id)
    .map(e => `  { id: ${e.id}, relsXml: \`${escapeTemplate(e.relsXml)}\` },`)
    .join('\n')
  const footer = `\n]\n`
  return header + body + footer
}

async function main() {
  const [layoutsPath, relsPath] = process.argv.slice(2)
  if (!layoutsPath || !relsPath) {
    die('Usage: node tools/ingest-layouts.mjs <layouts.txt> <rels.txt>')
  }
  const lp = resolve(WORKSPACE_ROOT, layoutsPath)
  const rp = resolve(WORKSPACE_ROOT, relsPath)
  if (!existsSync(lp)) die(`Layouts file not found: ${lp}`)
  if (!existsSync(rp)) die(`Rels file not found: ${rp}`)

  const layoutsText = await readFile(lp, 'utf8')
  const relsText = await readFile(rp, 'utf8')
  const layouts = parseLayouts(layoutsText)
  const rels = parseRels(relsText)

  if (layouts.length === 0) die('No layout entries found')
  if (rels.length === 0) die('No rels entries found')
  validate(layouts, rels)

  const layoutsTs = generateLayoutsTs(layouts)
  const relsTs = generateRelsTs(rels)

  await writeFile(OUT_LAYOUTS_TS, layoutsTs, 'utf8')
  await writeFile(OUT_RELS_TS, relsTs, 'utf8')

  console.log(`[ingest-layouts] Wrote ${OUT_LAYOUTS_TS}`)
  console.log(`[ingest-layouts] Wrote ${OUT_RELS_TS}`)
  console.log(`[ingest-layouts] Done. Build or run your code now.`)
}

main().catch(err => die(err?.stack || String(err)))
